<?php
function newuser_menu()
{
	return array(
		"newuser/set-stage/%"	=> array(
			"page callback"		=> "newuser_ajax_set_stage",
			"page arguments"	=> array(2),
			"access arguments"	=> array("access content"),
			"type"				=> MENU_CALLBACK,
		),
	);
}

function newuser_user($op, &$edit, &$account, $category=null)
{
	switch ($op)
	{
		case "insert":
			newuser_set_stage($account->uid);
			break;
		case "delete":
			$sql = "DELETE FROM {newuser_user_stage}
					WHERE `uid`=%d";
			db_query($sql, $account->uid);
	}
}

function newuser_theme()
{
	return array(
		"newuser_tutorial"			=> array(
			"arguments"	=> array("stage_html" => "", "header_html" => ""),
			"template"	=> "templates/new_user/tutorial",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"newuser_tutorial_stage"	=> array(
			"arguments"	=> array("stage" => false, "is_last_stage" => false),
			"template"	=> "templates/new_user/stage",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"newuser_tutorial_stage_header"	=> array(
			"arguments"	=> array("stage" => false, "user_stage" => 0),
			"template"	=> "templates/new_user/stage-header",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
	);
}

function newuser_preprocess_profile_ext_dashboard(&$vars)
{
	global $user;
	
	$user_stage = newuser_get_stage($user->uid);
	$stages = module_invoke_all("newuser_tutorial", $user, $user_stage);
	
	if (empty($stages) || $user_stage >= count($stages))
	{
		return;
	}
	
	usort($stages, function($a, $b)
	{
		return $a['stage'] <= $b['stage'] ? -1 : 1;
	});
	
	drupal_add_css("themes/vibio/css/newuser.css");
	drupal_add_js("themes/vibio/js/newuser.js");
	drupal_add_js(array(
		"newuser" => array(
			"current_stage"	=> $user_stage,
			"stages"		=> $stages,
		)
	), "setting");
	
	$stage_html = "";
	$header_html = theme("newuser_tutorial_stage_header", array("stage" => -1, "header" => t("Create Account")));
	foreach ($stages as $i => $stage)
	{
		$header_html .= theme("newuser_tutorial_stage_header", $stage, $user_stage + 1);
		
		if ($stage['stage'] <= $user_stage)
		{
			continue;
		}
		
		$stage_html .= theme("newuser_tutorial_stage", $stage, $i == count($stages) - 1);
	}
	$header_html .= theme("newuser_tutorial_stage_header", array("stage" => $i + 2, "header" => t("Use Vibio!")), $user_stage + 1);
	
	$vars['newuser_tutorial'] = theme("newuser_tutorial", $stage_html, $header_html);
}

function newuser_ajax_set_stage($stage)
{
	global $user;
	exit(newuser_set_stage($user->uid, $stage));
}

function newuser_get_stage($uid)
{
	static $stages;
	
	if (isset($stages[$uid]))
	{
		return $stages[$uid];
	}
	
	$sql = "SELECT `stage`
			FROM {newuser_user_stage}
			WHERE `uid`=%d";
	$stage = db_result(db_query($sql, $uid));
	
	$stages[$uid] = $stage === false ? (int) newuser_set_stage($uid) : (int) $stage;
	return $stages[$uid];
}

function newuser_set_stage($uid, $stage=0)
{
	$sql = "REPLACE INTO {newuser_user_stage}
			SET `stage`=%d, `uid`=%d";
	db_query($sql, $stage, $uid);
	
	return $stage;
}
?>