<?php
function profile_ext_service_perm()
{
	return array(
		"profile_ext_service remote_user",
	);
}

function profile_ext_service_service()
{
	return array(
		array(
			"#method"	=> "profile_ext.home",
			"#callback"	=> "profile_ext_service_home",
			"#access arguments"	=> array("profile_ext_service remote_user"),
			"#file"		=> array(
				"file"	=> "inc",
				"module"=> "profile_ext_service",
			),
			"#return"	=> "struct",
		),
	);
}
?>