<?php
function product_perm()
{
	return array(
		"product admin",
	);
}

function product_menu()
{
	return array(
		"admin/settings/product-catalog"	=> array(
			"title"				=> "Product Catalog",
			"description"		=> "Change settings related to the product catalog",
			"page callback"		=> "drupal_get_form",
			"page arguments"	=> array("product_admin"),
			"access arguments"	=> array("product admin"),
			"file"				=> "product.forms.php",
		),
		"product/%node/add-to-inventory"	=> array(
			"title callback"	=> "_product_inventory_add_title",
			"title arguments"	=> array(1),
			"page callback"		=> "product_add_to_inventory",
			"page arguments"	=> array(1),
			"access arguments"	=> array("create vibio_item content"),
			"file"				=> "product.pages.php",
			"type"				=> MENU_CALLBACK,
		),
	);
}

function product_external_search($args)
{
	if (!($provider = variable_get("product_source", false)) || !function_exists("{$provider}_product_search"))
	{
		return false;
	}
	if (!is_array($keys))
	{
		$args = array("keywords"	=> $args);
	}
	
	$func = "{$provider}_product_search";
	$args['keywords'] = _product_remove_options($args['keywords']);
	
	return $func($args);
}

function _product_remove_options($keys)
{
	return preg_replace('/(^| )([a-z0-9]+):(.*)( |$)/i', '', $keys);
}

function _product_inventory_add_title($product)
{
	return t("Add \"!product\" to your inventory", array("!product" => $product->title));
}
?>