<?php
require_once("vibio_item.inc.php");

define("VIBIO_ITEM_TYPE_OWN", 1);
define("VIBIO_ITEM_TYPE_SELL", 2);

function vibio_item_form_alter(&$form, &$state, $id)
{
	global $user;
	
	if ($id == "vibio_item_node_form")
	{	
		_vibio_item_unset($form);
		_vibio_item_defaults($form);
	}
	elseif ($id == "search_form" && $form['module']['#value'] == "vibio_item" && $user->uid > 0)
	{
		$options = _vibio_item_user_options();
		if (!empty($form['#parameters'][3]))
		{
			preg_match('/(\s+)users:([a-z]+)/i', $form['#parameters'][3], $defaults);
			$default_user_option = array_flip($options);
			$default_user_option = $defaults[2];
		}
		
		$form['vibio_advanced'] = array(
			"#type"			=> "fieldset",
			"#title"		=> t("Advanced"),
			"#collapsible"	=> true,
			"#collapsed"	=> false,
			"search_users"	=> array(
				"#type"			=> "select",
				"#title"		=> t("Search Users"),
				"#options"		=> $options,
				"#default_value"=> $default_user_option,
			),
		);
		
		$form["#validate"][] = "vibio_item_search_validate";
	}
	elseif ($id == "search_theme_form")
	{
		$form['#submit'][] = "vibio_item_search_submit";
	}
}

function vibio_item_search_validate($form, &$state)
{
	$vals = &$state['values'];
	$keys = $vals['processed_keys'];
	$user_options = _vibio_item_user_options();
	
	if (array_key_exists($vals['search_users'], $user_options))
	{
		$keys = preg_replace('/(\s+)users:([a-z]+)/i', '', $keys); //remove any existing value
		$keys .= " users:{$vals['search_users']} ";
	}
	
	form_set_value($form['basic']['inline']['processed_keys'], urldecode(trim($keys)), $state);
}

function vibio_item_search($op="search", $keys=null)
{
	switch ($op)
	{
		case "name":
			return t("Vibio");
		case "search":
			return _vibio_item_search($keys);
	}
}

//this is how i change the default tab
function vibio_item_search_submit($form, &$state)
{
	$form_id = $form['form_id']['#value'];
	$state['redirect'] = 'search/vibio_item/'.trim($state['values'][$form_id]);
}

function vibio_item_preprocess_node(&$vars)
{
	if (!$vars['teaser'] && $vars['node']->type == "vibio_item" && !_vibio_item_access($vars['node']))
	{
		$referrer = !empty($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '';
		drupal_set_message(t("The owner has decided not to show that item"), "error");
		drupal_goto($referrer);
	}
}
?>