<?php
require_once("vibio_item.inc.php");

define("VIBIO_ITEM_TYPE_OWN", 1);
define("VIBIO_ITEM_TYPE_SELL", 2);

function vibio_item_exit($destination=null)
{
	if ($destination && !empty($_GET['searchcrumb']) && strpos($destination, "?") === false && preg_match('/node\/([0-9]+)$/i', $destination, $matches))
	{
		drupal_goto($matches[0], "searchcrumb={$_GET['searchcrumb']}"); //hopefully i don't endlessly loop here...
	}
}

function vibio_item_theme(&$existing)
{
	return array(
		"vibio_item_user_other_items"	=> array(
			"arguments" => array("node" => false, "display" => array()),
			"template"	=> "templates/vibio_item/other-items",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"vibio_item_images"				=> array(
			"arguments"	=> array("images"	=> array()),
			"template"	=> "templates/vibio_item/additional-images",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
	);
}

function vibio_item_form_alter(&$form, &$state, $id)
{
	global $user;
	
	if ($id == "vibio_item_node_form")
	{	
		_vibio_item_unset($form);
		_vibio_item_defaults($form);
	}
	elseif ($id == "search_form" && $form['module']['#value'] == "vibio_item" && $user->uid > 0 && !module_exists("product"))
	{
		$options = _vibio_item_user_options();
		if (!empty($form['#parameters'][3]))
		{
			preg_match('/(\s+)users:([a-z]+)/i', $form['#parameters'][3], $defaults);
			$default_user_option = array_flip($options);
			$default_user_option = $defaults[2];
		}
		
		$form['vibio_advanced'] = array(
			"#type"			=> "fieldset",
			"#title"		=> t("Advanced"),
			"#collapsible"	=> true,
			"#collapsed"	=> false,
			"search_users"	=> array(
				"#type"			=> "select",
				"#title"		=> t("Search Users"),
				"#options"		=> $options,
				"#default_value"=> $default_user_option,
			),
		);
		
		$form["#validate"][] = "vibio_item_search_validate";
	}
	elseif ($id == "search_theme_form")
	{
		//$form['#submit'][] = "vibio_item_search_submit";
	}
}

function vibio_item_form_node_delete_confirm_alter(&$form, &$state)
{
	$node = node_load($form['nid']['#value']);

	if ($node->type != "vibio_item")
		return;

	$image = _vibio_item_get_image($node->nid);
	drupal_set_title(t("Are you sure you want to delete?"));

	$form['description']['#value'] = "
		<table class='vibio_item_delete_summary'>
			<tr>
				<td>
					<a href='/node/{$node->nid}'>
						<img src='$image' />
					</a>
				</td>
				<td class='node_info'>
					<a href='/node/{$node->nid}'>
						{$node->title}
					</a>
				</td>
			</tr>
		</table>
		{$form['description']['#value']}
	";
}

function vibio_item_search_validate($form, &$state)
{
	$vals = &$state['values'];
	$keys = $vals['processed_keys'];
	$user_options = _vibio_item_user_options();
	
	if (array_key_exists($vals['search_users'], $user_options))
	{
		$keys = preg_replace('/(\s+)users:([a-z]+)/i', '', $keys); //remove any existing value
		$keys .= " users:{$vals['search_users']} ";
	}
	
	form_set_value($form['basic']['inline']['processed_keys'], urldecode(trim($keys)), $state);
}

function vibio_item_search($op="search", $keys=null)
{
	switch ($op)
	{
		case "name":
			return t("Vibio");
		case "search":
			return _vibio_item_search($keys);
	}
}

//this is how i change the default tab
function vibio_item_search_submit($form, &$state)
{
	$form_id = $form['form_id']['#value'];
	$state['redirect'] = 'search/vibio_item/'.trim($state['values'][$form_id]);
}

function vibio_item_preprocess_node(&$vars)
{
	if (!$vars['teaser'] && $vars['node']->type == "vibio_item")
	{	
		if (!_vibio_item_access($vars['node']))
		{
			$referrer = !empty($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '';
			drupal_set_message(t("The owner has decided not to show that item"), "error");
			drupal_goto($referrer);
		}
		else
		{
			$node = $vars['node'];
			$images = array();
			if (!empty($node->field_main_image[0]['filepath']))
			{
				$images[] = file_create_url($node->field_main_image[0]['filepath']);
			}
			
			if (!empty($node->field_images))
			foreach ($node->field_images as $image)
			{
				if (file_exists($image['filepath']))
				{
					$images[] = file_create_url($image['filepath']);
				}
			}
			
			$extra_images = module_invoke_all("vibio_item_images", $node->nid);
			$images = array_merge($extra_images, $images);
			$vars['item_extra_images'] = theme("vibio_item_images", $images);
		}
	}
}

function vibio_item_preprocess_vibio_item_user_other_items(&$vars)
{
	$display_type = module_exists("collection") ? "collection" : "inventory";
	$u = user_load($vars['node']->uid);
	
	if ($display_type == "collection")
	{
		module_load_include("inc", "collection");
		
		$display = t("\"!current_item\" is part of !user's following collections:", array("!user" => l($u->name, "user/{$u->uid}"), "!current_item" => $vars['node']->title));
		$display .= "<ul>";
		
		foreach (collection_get_item_cid($vars['node']->nid) as $cid)
		{
			$collection = collection_load($cid);
			$display .= "<li><a href='/collections/{$cid}'>{$collection['title']}</a></li>";
		}
		$display .= "</ul>";
		$display .= t("!view_collections of !user's collections", array("!view_collections" => l(t("View all"), "user/{$u->uid}/inventory"), "!user" => l($u->name, "user/{$u->uid}")));
	}
	else
	{
		$display = t("!browse more of !user's items", array("!user" => $u->name, "!browse" => l(t("Browse"), "user/{$u->uid}/inventory")));
	}
	
	$vars['display'] = $display;
}

function vibio_item_views_api()
{
	return array(
		"api"	=> 2,
	);
}
?>
