<?php

/**
 * Menu link to an invite page
 */
function vibio_invite_menu(){
  $items['invite'] = array(
    'title' => 'Vibio Invite',
    'page callback' => 'vibio_invite_display_page',
    'description' => 'Invite friends to Vibio',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );

  $items['admin/vibio_invite'] = array(
    'title' => 'Vibio Invite Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vibio_invite_admin'),
    'description' => 'Settings for Vibio cross-platform invitations',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

function vibio_invite_admin($form_state){
  $form['twitter_message'] = array(
      '#type' => 'textarea',
      '#title' => 'Twitter Message',
      '#description' => 'This is the message that will be posted to twitter along with
        an invitation URL to Vibio. Remember that the invitation URL will be about
        25 characters, so keep your message short.',
      '#default_value' => "Join me on @vibio and checkout my collections!",
  );

  $form['invite_link'] = array(
      '#type' => 'textfield',
      '#title' => 'Invitation Link',
      '#description' => 'The page that invited users will be sent to, relative to webroot',
      '#default_value' => 'user/register',
  );

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Save'),
  );

  return $form;

  //@todo add an ajax callback to have a dynamic facebook message for the request.
}

/**
 * Sets the admin variables.
 * 
 * @param <type> $form
 * @param <type> $form_state
 */
function vibio_invite_admin_submit($form, &$form_state){
  //Adding a space because the URL will be appended the end
  variable_set('vibio_invite_twitter_message', $form_state['values']['twitter_message'] . ' ');
  $url = url($form_state['values']['invite_link']);
  variable_set('vibio_invite_link', $url);
}

/**
 * Block definition, implements hook_block()
 *
 * @param <type> $op
 * @param <type> $delta
 * @param <type> $edit
 * @return string
 */
function vibio_invite_block($op = 'list', $delta = 'vibio_invite', $edit = array()) {
  if ($op == 'list') {
    $block['vibio_invite']['info'] = t('Vibio Invites');
    $block['vibio_invite']['visibility'] = 0;
    $block['vibio_invite']['pages'] = 'vibio_invite';
    return $block;
  }
  elseif ($op == 'view' && $delta == 'vibio_invite') {
    $block['subject'] = t('Invite Friends');
    $block['content'] = theme('vibio_invite_display');
    return $block;
  }
}

/**
 * Implementes hook_theme()
 *
 * @return Array
 */
function vibio_invite_theme(){
  return array(
      'vibio_invite_display' => array(
          'template' => 'templates/vibio-invite-block-content',
          'path' => drupal_get_path('module', 'vibio_invite'),
      )
  );  
}

/**
 * Generates the link variables for the invite block template
 *
 * @return string
 */
function vibio_invite_preprocess_vibio_invite_display(&$vars){
  global $base_url;
  $app_id = variable_get('fboauth_id', '');
  $url = variable_get('vibio_invite_link');
  
  //URL to send an invitation message via Twitter
  if(module_exists('shorten')){
    $twitter_url = shorten_url($url, 'TinyURL');
  }else{
    $twitter_url = $url;
  }
  $twitter_message = variable_get('vibio_invite_twitter_message');

  $vars['twitter_url'] = 'http://twitter.com/home?status=' . $twitter_message . $twitter_url; //array('attributes' => array('target' => '_blank')));

  //Facebook URL for request
  //@TODO: use request dialog instead of send
  $vars['fb_url'] = url("https://www.facebook.com/dialog/send", array('query' => array('app_id' => $app_id, 'name' => "Join Vibio to share your collections and see your friends's things", 'link' => $base_url, 'redirect_uri' => $base_url . "/invite")));

  //URL to the current email invite page
  $vars['email_url'] = url('contacts/invite');
}

function vibio_invite_display_page(){
  //In the future we may want to use the FB JS SDK here, but currently having problems-alec
  //vibio_fboauth_add_js();
  //Add the JS for the FB request dialog and possibly for twitter
  //drupal_add_js(drupal_get_path('module', 'vibio_invite') . '/js/vibio_invite.js');
  return theme('vibio_invite_display');
}


?>
