<?php
function fb_perm()
{
	return array(
		"fb admin",
		"fb user",
	);
}

function fb_menu()
{
	return array(
		"admin/settings/facebook"	=> array(
			"title"				=> "Facebook Settings",
			"page callback"		=> "drupal_get_form",
			"page arguments"	=> array("facebook_admin"),
			"access arguments"	=> array("fb admin"),
			"file"				=> "fb.admin.inc",
			"type"				=> MENU_NORMAL_ITEM,
		),
		"facebook/signup"		=> array(
			"title"				=> "Sign Up Using Facebook",
			"page callback"		=> "fb_user_signup",
			"access arguments"	=> array("fb user"),
			"file"				=> "fb.pages.inc",
			"type"				=> MENU_CALLBACK,
		),
		"facebook/link-account"	=> array(
			"page callback"		=> "fb_user_link_account",
			"access arguments"	=> array("fb user"),
			"file"				=> "fb.pages.inc",
			"type"				=> MENU_CALLBACK,
		),
		"facebook/remove-account"	=> array(
			"page callback"		=> "fb_user_remove_account",
			"access arguments"	=> array("fb user"),
			"file"				=> "fb.pages.inc",
			"type"				=> MENU_CALLBACK,
		),
	);
}

function fb_user($op, &$edit, &$u, $category=null)
{
	switch ($op)
	{
		case "insert":
			if ($edit['fb_id'])
			{
				module_load_include("inc", "fb");
				fb_save_user($u, $edit['fb_id']);
				$edit['fb_id'] = null;
			}
			break;
		case "delete";
			$sql = "DELETE FROM {fb_users}
					WHERE `uid`=%d";
			db_query($sql, $u->uid);
	}
}

function fb_block($op="list", $delta=0, $edit=array())
{
	switch ($op)
	{
		case "list":
			return array(
				"fb_login"			=> array(
					"info"	=> t("Facebook Login"),
				),
				"fb_dialogs"	=> array(
					"info"	=> t("Facebook Dialogs"),
				),
				"fb_api_init"		=> array( // this block is REQUIRED for any fb things to work.
					"info"	=> t("Facebook API Init"),
				),
			);
		case "view":
			switch ($delta)
			{
				case "fb_login":
					return array(
						"subject"	=> "",
						"content"	=> theme("fb_login_block"),
					);
				case "fb_api_init":
					drupal_add_css("sites/all/themes/vibio/css/facebook.css");
					module_load_include("inc", "fb");
					fb_add_js();
					
					return array(
						"subject"	=> "",
						"content"	=> "<div id='fb-root'></div>",
					);
				case "fb_dialogs":
					return array(
						"subject"	=> "",
						"content"	=> theme("fb_dialogs"),
					);
			}
	}
}

function fb_theme(&$existing, $type, $theme, $path)
{
	return array(
		"fb_login_block"	=> array(
			"arguments"	=> array(),
			"template"	=> "templates/facebook/login-block",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"fb_share"			=> array(
			"arguments"	=> array("node"	=> false),
			"template"	=> "templates/facebook/share",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"fb_dialogs"		=> array(
			"arguments"	=> array(),
			"template"	=> "templates/facebook/dialogs",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"fb_wrong_login"	=> array(
			"arguments"	=> array(),
			"template"	=> "templates/facebook/wrong-login",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"fb_login_prompt"	=> array(
			"arguments"	=> array(),
			"template"	=> "templates/facebook/login-prompt",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"fb_share_success"	=> array(
			"arguments"	=> array(),
			"template"	=> "templates/facebook/share-success",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
	);
}

function fb_preprocess_fb_share(&$vars)
{
	if (is_numeric($vars['node']))
	{
		$vars['node'] = node_load($vars['node']);
	}
}

function fb_network_get_userinfo($uid)
{
	$sql = "SELECT `fb_id`
			FROM {fb_users}
			WHERE `uid`=%d";
	if (!($fb_id = db_result(db_query($sql, $uid))))
	{
		return array();
	}
	
	return array(
		"fb_id"	=> array(
			$fb_id,
		)
	);
}

function fb_profile_ext_external_account_data()
{
	return array(
		"fb_id"	=> array(
			"id"	=> "fb",
			"name"	=> "Facebook",
			"title"	=> t("Facebook Account"),
			"remove"=> array(
				"class"	=> "fb_remove_account",
			),
			"add"	=> array(
				"multiple"	=> false,
				"class"		=> "fb_link_account",
			),
		),
	);
}
?>