<?php
function ur_generate_menu()
{
	return array(
		"admin/generate/user-relationships"	=> array(
			"title"				=> "User Relationships",
			"page callback"		=> "drupal_get_form",
			"page arguments"	=> array("ur_generate_admin"),
			"access arguments"	=> array("ur_generate admin"),
			"type"				=> MENU_NORMAL_ITEM,
		),
	);
}

function ur_generate_admin()
{
	return array(
		"#prefix"			=> t("Make sure to turn off UR emails on the !settings page!", array("!settings" => l("settings", "admin/user/relationships/settings"))),
		"generate_amount"	=> array(
			"#title"		=> t("Amount of relationships"),
			"#type"			=> "textfield",
			"#size"			=> 6,
			"#required"		=> true,
			"#default_value"=> 200,
		),
		"submit"			=> array(
			"#type"	=> "submit",
			"#value"=> t("generate"),
		),
	);
}

function ur_generate_admin_validate($form, &$state)
{
	if (!is_numeric($state['values']['generate_amount']))
	{
		form_set_error("generate_amount", t("Amount of relationships must be numeric"));
	}
}

function ur_generate_admin_submit($form, &$state)
{
	set_time_limit(0);
	
	$amount = $state['values']['generate_amount'];
	$rtid = 1;
	
	for ($i = 0; $i < $amount; ++$i)
	{
		$sql = "SELECT `uid`, `name`
				FROM {users}
				ORDER BY RAND()
				LIMIT 1";
		$user1 = db_fetch_object(db_query($sql));
		
		$sql = "SELECT `uid`, `name`
				FROM {users}
				WHERE `uid` != %d
					AND `uid` NOT IN (
						SELECT `requestee_id`
						FROM {user_relationships}
						WHERE `requester_id`=%d
					)
				ORDER BY RAND()
				LIMIT 1";
		if (!($user2 = db_fetch_object(db_query($sql, $user1->uid, $user1->uid))))
		{
			continue;
		}
		
		$rel = new stdClass;
		$rel->requester_id = $user1->uid;
		$rel->requester = $user1;
		$rel->requestee_id = $user2->uid;
		$rel->requestee = $user2;
		$rel->approved = 1;
		$rel->rtid = 1;
		$rel->name = "Connection";
		
		user_relationships_save_relationship($rel, "approve");
	}
	
	drupal_set_message("done");
}
?>