<?php
define("COLLECTION_DESCRIPTION_MAX_LENGTH", 65535);
define("COLLECTION_TITLE_MAX_LENGTH", 255);
define("COLLECTION_ITEM_PREVIEW_MAX_TITLE_LENGTH", 16);

function collection_perm()
{
	return array(
		"collections user",
		"collections viewer",
	);
}

function collection_menu()
{
	return array(
		"collections/manage"		=> array(
			"title"				=> "Manage Your Collections",
			"page callback"		=> "collection_manage",
			"access arguments"	=> array("collections user"),
			"file"				=> "collection.pages.inc",
			"type"				=> MENU_SUGGESTED_ITEM,
		),
		"collections/manage/%collection"	=> array(
			"title callback"	=> "collection_title",
			"title arguments"	=> array(2),
			"page callback"		=> "drupal_get_form",
			"page arguments"	=> array("collection_edit", 2),
			"access callback"	=> "collection_manage_collection_access",
			"access arguments"	=> array(2),
			"file"				=> "collection.pages.inc",
			"type"				=> MENU_CALLBACK,
		),
		"collections/new"		=> array(
			"title"				=> "New Collection",
			"page callback"		=> "drupal_get_form",
			"page arguments"	=> array("collection_edit"),
			"access arguments"	=> array("collections user"),
			"file"				=> "collection.pages.inc",
			"type"				=> MENU_CALLBACK,
		),
		"collections/%collection"	=> array(
			"title callback"	=> "collection_title",
			"title arguments"	=> array(1),
			"page callback"		=> "collection_view_collection",
			"page arguments"	=> array(1),
			"access callback"	=> "collection_access_collection",
			"access arguments"	=> array(1),
			"file"				=> "collection.pages.inc",
			"type"				=> MENU_CALLBACK,
		),
		"collections/%/view-all"	=> array(
			"title"				=> "All Items",
			"page callback"		=> "collection_view_all_user_items",
			"page arguments"	=> array(1),
			"access arguments"	=> array("collections viewer"),
			"file"				=> "collection.pages.inc",
			"type"				=> MENU_CALLBACK,
		),
	);
}

function collection_block($op="list", $delta=0, $edit=array())
{
	switch ($op)
	{
		case "list":
			return array(
				"random_collection"	=> array(
					"info"	=> t("Random Collection"),
					"cache"	=> BLOCK_NO_CACHE,
				),
			);
		case "view":
			switch ($delta)
			{
				case "random_collection":
					global $user;
					module_load_include("inc", "collection", "collection.pages");

					return array(
						"subject"	=> "",
						"content"	=> collection_random_collection($user),
					);
			}
	}
}

function collection_theme(&$existing)
{
	return array(
		"collection_list_item" => array(
			"arguments"	=> array("collection" => array(), "access" => false, "show_preview" => true),
			"template"	=> "templates/collections/collection",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"collection_list_item_preview"	=> array(
			"arguments"	=> array("item" => array()),
			"template"	=> "templates/collections/collection-item-preview",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"collection_view_collection"	=> array(
			"arguments"	=> array("collection_owner" => 1, "collection_display"	=> "", "collection_sidebar" => array()),
			"template"	=> "templates/collections/collection-view",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"collection_sidebar_item"		=> array(
			"arguments"	=> array("collection_item" => array()),
			"template"	=> "templates/collections/sidebar-item",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"collection_sidebar_collection"	=> array(
			"arguments"	=> array("collection" => array(), "item_html" => ""),
			"template"	=> "templates/collections/sidebar-collection",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"collection_random_collection"	=> array(
			"arguments"	=> array("collection" => false),
			"template"	=> "templates/collections/random-collection",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
	);
}

function collection_preprocess_collection_view_collection(&$vars)
{
	global $user;

	$collection_html = "";
	foreach ($vars['collection_sidebar'] as $c)
	{
		$item_html = "";
		foreach($c->items as $item)
		{
			$item_html .= theme("collection_sidebar_item", $item);
		}

		$collection_html .= theme("collection_sidebar_collection", $c, $item_html);
	}

	$vars['collection_sidebar_output'] = $collection_html;

	if ($vars['collection_owner'] == $user->uid)
	{
		$add_text = t("Add Item");
		$vars['collection_owner_name'] = t("Your");
		$vars['add_item_link'] = "<a href='/product/add'>
			<div class='button_left'></div>
			<div class='button_mid'>
				<span class='form-submit'>
					$add_text
				</span>
			</div>
			<div class='button_right'></div>
			<div class='clear'></div></a>
		";
	}
	else
	{
		$owner = user_load($vars['collection_owner']);
		$vars['collection_owner_name'] = "{$owner->name}'s";
	}
}

function collection_preprocess_collection_list_item(&$vars)
{
	if(empty($vars['collection']))
		return;

	module_load_include("inc", "collection");

	$vars['collection']->is_owner = module_exists("privacy") ? $vars['access'] == PRIVACY_ONLYME : true;
	$vars['collection']->image = collection_get_image($vars['collection']->cid, false, $vars['access']);
	$vars['collection']->total_items = collection_get_num_items($vars['collection']->cid, $vars['access']);

	$share_html = "";
/*
	if($vars['collection']->is_owner ) {
		if(module_exists("fb"))
			$share_html .= 'x'.theme("fb_share", $vars['collection']->cid, "collection");
		if(module_exists("tweetassist"))
			$share_html .= theme("tweetassist_tweet", "collection", $vars['collection']->cid);
	}

 */
	$vars['collection']->share_html = $share_html;

	$categories = collection_get_categories($vars['collection']->cid);
	if(!empty($categories)) {
		$category_text = t("Tags: !categories", array("!categories" => implode(", ", $categories)));
		$vars['collection']->collection_categories = "<span class='collection_categories'>$category_text</span>";
	}
}

function collection_preprocess_collection_list_item_preview(&$vars)
{
	global $user;
	module_load_include('inc', 'product');
	$vars['item']->image = file_uncreate_url( _vibio_item_get_image($vars['item']->nid));
        $vars['item']->image = ltrim($vars['item']->image, '/');
	$vars['item']->for_sale = $vars['item']->node_data_field_posting_type_field_posting_type_value == VIBIO_ITEM_TYPE_SELL;
	$vars['item']->node_title = strlen($vars['item']->node_title) > COLLECTION_ITEM_PREVIEW_MAX_TITLE_LENGTH ? substr($vars['item']->node_title, 0, COLLECTION_ITEM_PREVIEW_MAX_TITLE_LENGTH)."..." : $vars['item']->node_title;

/*
	$share_html = "";
	if ($vars['item']->users_uid == $user->uid) {
		if(module_exists("fb"))
			$share_html .= 'y'.theme("fb_share", $vars['item']->nid, "node", "icon");
		if(module_exists("tweetassist"))
			$share_html .= theme("tweetassist_tweet", "node", $vars['item']->nid);
	}
*/
	$vars['share_links'] = $share_html;

	if (!$vars['item']->for_sale && $vars['item']->users_uid == $user->uid)
	{
		$options = array(
			"attributes"	=> array(
				"class"	=> "offer2buy_edit_post_type",
			),
		);
		$vars['item']->offer2buy_price = l(t("Sell"), "offer2buy/ajax/edit-post-type/{$vars['item']->nid}", $options);
	}
	elseif ($vars['item']->for_sale && $vars['item']->offer2buy_price > 0)
	{
		$vars['item']->offer2buy_price =  "$".$vars['item']->offer2buy_price;
	}
	elseif ($vars['item']->for_sale)
	{
		$vars['item']->offer2buy_price = t("Best Offer");
	}
	else
	{
		$vars['item']->offer2buy_price = t("<span class='bold-text'>Status:</span> Not for Sale");
	}
	//If the offer2buy module is active...
	if(module_exists('offer2buy')){
		//Insert an offer button or not for sale image
		$item = $vars['item'];
		$item->offer2buy['settings']['is_on_sale'] = $vars['item']->for_sale; 
		$vars['offer_button'] = theme('offer_button', $item, $user->uid);
	}
}

function collection_preprocess_page(&$vars)
{
	drupal_add_js("themes/vibio/js/collections.js");
	drupal_add_css("themes/vibio/css/collections.css");
}

function collection_nodeapi(&$node, $op, $a3=null, $a4=null)
{
	if ($node->type != "vibio_item")
	{
		return;
	}

	global $user;
	module_load_include("inc", "collection");

	switch ($op)
	{
		case "insert":
			$cids = isset($node->collection_info) ? $node->collection_info['cid'] : false;
			if ($cids)
			{
				$cids = implode(",", $cids);
				$sql = "SELECT `cid`, `title`
						FROM {collection}
						WHERE `cid` IN ($cids)";
				$res = db_query($sql);

				$collections = array();
				while ($row = db_fetch_object($res))
				{
					$collections[] = l($row->title, "collections/{$row->cid}");
				}

				$t_args = array(
					"!item" 		=> l($node->title, "node/{$node->nid}"),
					"!collections"	=> implode(", ", $collections),
				);

				$message = count($collections) > 1 ?
					t("!item has been created and added to the following collections: !collections", $t_args) :
					t("!item has been created and added to your !collections collection", $t_args);

				drupal_set_message($message);
			}
		case "update":
			$cids = isset($node->collection_info) ? $node->collection_info['cid'] : collection_get_item_cid($node->nid);
			unset($node->collection_info);

			$old_cids = $op == "update" ? collection_get_item_cid($node->nid) : array();
			$delete_cids = array_diff($old_cids, $cids);
			if (!empty($delete_cids))
			{
				$delete_cids = implode(",", $delete_cids);
				$sql = "DELETE FROM {collection_items}
						WHERE `item_nid`=%d
							AND `cid` IN ($delete_cids)";
				db_query($sql, $node->nid);
			}

			$sql = "INSERT INTO {collection_items}
					(`cid`, `item_nid`) VALUES";
			$vals = array();
			$args = array();
			foreach (array_diff($cids, $old_cids) as $cid)
			{
				$vals[] = "(%d, %d)";
				$args[] = $cid;
				$args[] = $node->nid;
			}

			if (!empty($vals))
			{
				$sql .= implode(",", $vals);
				db_query($sql, $args);
			}

			module_invoke_all("collection_update", $user->uid, array_unique(array_merge($cids, $old_cids)));
			break;
		case "delete":
			$cid = collection_get_item_cid($node->nid);
			$sql = "DELETE FROM {collection_items}
					WHERE `item_nid`=%d";
			db_query($sql, $node->nid);
			module_invoke_all("collection_delete_item", $user->uid, $cid, $node->nid);
			break;
	}
}

function collection_views_api()
{
	return array(
		"api"	=> 2,
	);
}

function collection_form_product_node_form_alter(&$form, &$state)
{
	if (module_exists("product") && !product_get_autoadd(false))
	{
		return;
	}

	if (!$form['#node']->nid) // only on new product nodes
	{
		collection_form_vibio_item_node_form_alter(&$form, &$state);
	}
}

function collection_form_vibio_item_node_form_alter(&$form, &$state)
{
	module_load_include("inc", "collection");

	// Empty collections?
	if (!$form['#node']->nid && 
			(count(collection_options()) < 1 )) {
		$default_array = collection_get_user_default(false, true);
		// collection_options seems to cache, so force it.  This is repeat
		//  code with collection_get_user_default which I expect will be gone
		//  in two weeks.
		$default = $default_array['cid'];
		$options = array();
		$options[$default] = 'Unsorted';
	} else {
		$options = collection_options();
	}
	
	if ($form['#node']->nid) //existing node
	{
		$default = collection_get_item_cid($form['#node']->nid);
	} 


	// Add the collection_info field to this form
	$form['collection_info'] = array(
		"#title"		=> t("Collection"),
		"#description"	=> t("Select which collections to add this item to. Choose all that apply."), //:" . '<p><strong><a href="/collections/new?automodalReload=true" class="automodal">* Add new collection</a></strong>'),

		"#type"			=> "fieldset",
		"#collapsible"	=> true,
		"#collapsed"	=> false,
		"#tree"			=> true,
		"cid"			=> array(
			"#type"			=> "select",
			"#required"		=> true,
			"#title"		=> t("Collection"),
			"#options"		=> $options, //collection_options(),
			"#default_value"=> $default,
			"#multiple"		=> true,
		),

		/* this was commented out, why?
			 --> doesn't seem to do anything at all
		"new_collection"=> array(
			"#type"			=> "textfield",
			"#title"		=> t("New Collection"),
			"#description"	=> t("Enter a name for this collection"),
		),
		*/
	);
}

function collection_product_inventory_quick_add($form_vals)
{
	global $user;

	module_load_include("inc", "collection");

	if ($form_vals['collection_info']['cid'] || !($default = collection_get_user_default($user->uid, true)))
	{
		return array();
	}

	return array(
		"collection_info"	=> array(
			"cid"	=> array($default => $default),
		),
	);
}

function collection_offer2buy_complete_actions($old_uid, $node)
{
	module_load_include("inc", "collection");
	$old_cid = collection_get_item_cid($node->nid);

	if (!($new_cid = collection_get_user_default($node->uid)))
	{
		$new_cid = collection_get_user_default($node->uid, true); //this will handle clearing the views caches for us...
	}
	else
	{
		module_invoke_all("collection_update", $node->uid, array($new_cid));
	}

	$sql = "DELETE FROM {collection_items}
			WHERE `item_nid`=%d";
	db_query($sql, $node->nid);

	$sql = "INSERT INTO {collection_items}
			(`cid`, `item_nid`) VALUES
			(%d, %d)";
	db_query($sql, $new_cid, $node->nid);

	module_invoke_all("collection_update", $old_uid, $old_cid);
}

function collection_form_views_exposed_form_alter(&$form, &$state)
{

	if ($form['#id'] == "views-exposed-form-user-collection-default") {
		$form['collection_order_by'] = array(
			"#type"		=> "select",
			"#title"	=> t("Sort"),
			"#weight"	=> 9,
			"#options"	=> array(
				"node_changed-desc"	=> t("Newest First"),
				"node_changed-asc"	=> t("Oldest First"),
			),
		);
		$form['order'] = array(
			"#type" => "hidden",
			"#value"=> isset($_GET['order']) ? $_GET['order'] : "node_changed",
		);
		$form['sort'] = array(
			"#type" => "hidden",
			"#value"=> isset($_GET['sort']) ? $_GET['sort'] : "node_changed",
		);

		$form['submit']['#weight'] = 10;
	}
	elseif (in_array($form['#id'], array("views-exposed-form-user-collections-default", "views-exposed-form-user-inventory-default")))
	{
		$label = t("View");
		$uid = $form['#parameters'][1]['view']->args[0];
		$collection = t("Collections");
		$all_items = t("All Items");
		$collection_default = $form['#id'] == "views-exposed-form-user-collections-default" ? "selected='selected'" : "";
		$items_default = $form['#id'] == "views-exposed-form-user-inventory-default" ? "selected='selected'" : "";

		/* $form['#suffix'] = "
			<div class='inventory_view_type'>
				<span>$label</span>
				<select class='inventory_view_type_select'>
					<option value='/user/{$uid}/inventory' $collection_default>$collection</option>
					<option value='/collections/{$uid}/view-all' $items_default>$all_items</option>
				</select>
			</div>
			<div class='clear'></div>
		";*/
	}
}

function collection_profile_ext_public_info($uid)
{
	module_load_include("inc", "collection");
	$collections = collection_get_collections($uid);
	$access = privacy_get_access_level($uid);

	foreach ($collections as $cid => $c)
	{
		if ($c['privacy'] > $access)
		{
			unset($collections[$cid]);
		}
	}

	return array(array(
		"weight"=> 0,
		"title"	=> t("Collections"),
		"data"	=> count($collections),
	));
}

function collection_badge_user_login($uid) {
	if (!($badge = badge_load_special("100_collections_6_months")) || badge_user_has_badge($badge->bid, $uid)) {
		return false;
	}

	$sql = "SELECT COUNT(*)
			FROM {collection}
			WHERE `uid`=%d";
	$total_collections = db_result(db_query($sql, $uid));

	if ($total_collections >= 100) {
		badge_give_badge($badge->bid, $uid);
	}
}

// warning: stephen cut and pasted some code, and found $cid being passed
//  here was an array.  Is this happening elsewhere?  It oddly works if
//  you comment out the the is_numeric test... $cid = array(26=>26) behaves
//  like $cid = 26
function collection_load($cid)
{
	if (!is_numeric($cid))
	{
		return false;
	}

	$sql = "SELECT c.*, u.name AS user_name
			FROM {collection} c JOIN {users} u ON c.`uid`=u.`uid`
			WHERE `cid`=%d";
	$collection = db_fetch_array(db_query($sql, $cid));
	$collection = array_merge($collection, module_invoke_all("collection_load", $collection, $as_uid)); // stephen notes: $as_uid, what is it, where from?
//dsm(array($cid,$collection));
	return $collection;
}

function collection_access_collection($collection)
{
	global $user;

	if ($user->uid == $collection['uid'])
	{
		return true;
	}
	elseif (isset($collection['privacy']) && module_exists("privacy"))
	{
		return privacy_get_access_level($collection['uid']) >= $collection['privacy'] && user_access("collections viewer");
	}
	else
	{
		return user_access("collections user");
	}
}

function collection_manage_collection_access($collection)
{
	global $user;

	if (is_numeric($collection))
	{
		$sql = "SELECT `uid`
				FROM {collection}
				WHERE `cid`=%d";
		$collection = db_fetch_array(db_query($sql, $collection));
	}

	return $user->uid == $collection['uid'];
}

function collection_title($collection)
{
	return $collection['title'];
}
?>
