<?php
define("OVERRIDES_FILE_DOWNLOAD_DIRECT", 5);

function overrides_menu_alter(&$menu)
{
	$menu['user/%/messages']['type'] = MENU_CALLBACK;
	$menu['user/%user_category/edit']['type'] = MENU_CALLBACK;
	$menu['user/%user/openid']['type'] = MENU_CALLBACK;
}

function overrides_theme()
{
	return array(
		"overrides_search_type_select"	=> array(
			"arguments"	=> array("search_types" => array()),
			"template"	=> "templates/overrides/search-type-select",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
	);
}

function overrides_form_system_file_system_settings_alter(&$form, &$state)
{
	$form['file_downloads']['#options'][OVERRIDES_FILE_DOWNLOAD_DIRECT] = t("Separate server");
	$form['file_downloads']['#description'] .= " ".t("Choosing Separate vhost requires that the File URL is filled in with a valid url that will take you to the File system path.");
	$form['overrides_file_url'] = array(
		"#type"			=> "textfield",
		"#title"		=> t("File URL"),
		"#description"	=> t("The URL to access the file system path. No trailing slash plz."),
		"#default_value"=> variable_get("overrides_file_url", ""),
		"#weight"		=> -5,
	);
}

function overrides_file_url_alter(&$path)
{
	$upload_dir = file_directory_path();
	$file_url = variable_get("overrides_file_url", false);
	
	if ($file_url && variable_get('file_downloads', FILE_DOWNLOADS_PUBLIC) == OVERRIDES_FILE_DOWNLOAD_DIRECT && strpos($path, $upload_dir) === 0)
	{
		$path = str_replace($upload_dir, $file_url, $path);
	}
}

function overrides_form_search_theme_form_alter(&$form, &$state)
{
	$form['submit']['#value'] = " ";
	$form['#submit'][] = "overrides_search_submit";

	$form['search_type'] = array(
		"#type"			=> "hidden",
		"#default_value"=> "vibio_item",
	);

	$form['search_type_select'] = array(
		"#type"		=> "markup",
		"#value"	=> theme("overrides_search_type_select", overrides_allowed_search_types()),
		"#weight"	=> -10,
	);

	$form['search_theme_form']['#title'] = "";
}

function overrides_search_submit($form, &$state)
{
	$allowed_searches = overrides_allowed_search_types();
	$default_search = "vibio_item";
	$search_type = array_key_exists($state['values']['search_type'], $allowed_searches) ? $state['values']['search_type'] : $default_search;
	$search_term = trim($state['values'][$form['form_id']['#value']]);

	$state['redirect'] = "search/$search_type/$search_term";
}

function overrides_allowed_search_types()
{
	return array(
		"vibio_item"=> array(
			"title"	=> t("Search Items"),
			"image"	=> "/themes/vibio/images/icons/default_item.png",
		),
		"user"		=> array(
			"title"	=> t("Search Users"),
			"image"	=> "/themes/vibio/images/icons/default_user.png",
		),
	);
}
?>
