<?php
/**
 * @vibio_item_add_page.module
 * Create pages and whatever else is needed to navigate through the
 * process of adding an item.  New work will include menus, page design,
 * integrating search, integrating existing ways to add an item or product. 
 */

/**
 * Implementation of hook_perm().
 * Needed? No. Use some other access.
 */

/** * Implementation of hook_menu().
 */
function vibio_item_add_page_menu() {
  $items['add_an_item_temp'] = array(
    'title' => 'Add an Item',
    'description' => t('Add an item to your have, want or like list.'),
    'page callback' => 'vibio_add_item_page_page', //'drupal_get_form',
  //'page arguments' => array('module_builder_page'),
  //'file' => 'xxx.pages.inc',
  //!!!'access arguments' => array('access module builder'),
  'type' => MENU_NORMAL_ITEM,
  );
  return $items;
} 

/**
 * Add Item page.
 */
function vibio_add_item_page_page() {
	global $user;
$active_find = "active_find";
$output = "<span class='arrow $active_find'>Find Your Item</span><span class='arrow $active_add'>Add it to Your Profile</span><span class='arrow $active_share'>Share Your Style</span>";
$output .= '<p style="border: 2px solid blue; padding: 20px;">-- insert search for your item / find your item --';
$output = "<p>Quickly find your item in our product list and add it to your Style Profile.  If it's listed, you'll save time uploading photos and descriptions, and your item will be easier to find.

<p>If this search doesn't show your item, then you'll add it to our product list on the next page.";


	return $output;
}

/**
 * Implementation of hook_theme()
 */
function vibio_item_add_page_theme() {
  return array(
    'vibio_item_add_page_theme_form' => array(
      'arguments' => array('form' => NULL),
      'template' => 'vibio_item_add_page-theme-form',
    ),
  );
}
