<?php

include_once('vibio_product_displays.features.inc');

function vibio_product_displays_menu() {
  $items['for-sale'] = array(
    'title' => t('For Sale'),
    'description' => t('View products that people have and are selling.'),
    'type' => MENU_NORMAL,
    'page callback' => 'vibio_product_displays_for_sale',
    'access callback' => 'user_is_logged_in',
  );
  $items['recent'] = array(
    'title' => t('Recent'),
    'description' => t("View products that have recently entered people's collections."),
    'type' => MENU_NORMAL,
    'page callback' => 'vibio_product_displays_recent',
    'access callback' => 'user_is_logged_in',
  );
  return $items;
}

function vibio_product_displays_for_sale() {
  $content = views_embed_view('all_products_for_sale', 'page');
  return $content;
}

function vibio_product_displays_recent() {
  $content = views_embed_view('recent_products', 'page');
  return $content;
}

function vibio_product_displays_views_pre_render(&$view) {
  if ($view->name == 'all_products_for_sale' || $view->name == 'Wantlist') {
    $fid_alias = $view->field['field_main_image_fid']->field_alias;
    // Fake the _list and _data properties
    $fid_stub = substr($fid_alias, 0, -4);
    $fid_alias_fid = $fid_stub . '_fid';
    $fid_alias_list = $fid_alias . '_list';
    $fid_alias_data = $fid_alias . '_data';
    foreach ($view->result as $row) {
      if ($row->{$fid_alias_fid}) {
        continue;
      }
      else {
        // Grab the image from the parent product
        $product_nid = db_result(db_query("select product_nid from {product_items} where item_nid=%d", $row->nid));

        // Load the image, whatever it is

        $field = content_fields('field_main_image');
        $db_info = content_database_info($field);
        $table = $db_info['table'];
        $fid_col = $db_info['columns']['fid']['column'];
        $list_col = $db_info['columns']['list']['column'];
        $data_col = $db_info['columns']['data']['column'];
        $product_image_row = db_fetch_object(db_query("select $fid_col, $list_col, $data_col from {%s}
            where nid = %d", $table, $product_nid));
        $row->{$fid_alias_fid} = $product_image_row->{$fid_col};
        $row->{$fid_alias_list} = $product_image_row->{$list_col};
        $row->{$fid_alias_data} = $product_image_row->{$data_col};
      }
    }
  }
}

function computed_field_field_item_count_compute($node, $field, &$node_field) {
  $node_field[0]['value'] = (int) db_result(db_query("select count(item_nid) from {product_items} where product_nid = %d", $node->nid));
}

function computed_field_field_item_count_display($field, $element, $node) {
  return $element['#item']['value'];
}

function _vibio_product_displays_homepage_print_google_conversion_code() {
  // code to track users who click ad, and then are logged in
  // assumed to be new users
  $conversion = '<!-- Google Code for Sign Up Conversion Page -->
    <script type="text/javascript">
      /* <![CDATA[ */
      var google_conversion_id = 1017452623;
      var google_conversion_language = "en";
      var google_conversion_format = "3";
      var google_conversion_color = "ffffff";
      var google_conversion_label = "J8y9CLGRqgIQz7CU5QM";
      var google_conversion_value = 0;
      /* ]]> */
    </script>
    <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
    </script>
    <noscript>
      <div style="display:inline;">
      <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1017452623/?label=J8y9CLGRqgIQz7CU5QM&guid=ON&script=0"/>
      </div>
    </noscript>';

  print $conversion;
}

