<?php
define("OFFER2BUY_MAX_PRICE", 1000000);
define("OFFER2BUY_MAX_COMMENT_LENGTH", 255);

require_once("offer2buy.actions.php");

function offer2buy_perm()
{
	return array(
		"offer2buy offer",
		"offer2buy admin",
	);
}

function offer2buy_menu()
{
	return array(
		"offer2buy"					=> array(
			"title"				=> "Offer2Buy Dashboard",
			"page callback"		=> "offer2buy_dashboard",
			"access arguments"	=> array("offer2buy offer"),
			"type"				=> MENU_NORMAL_ITEM,
		),
		"offer2buy/%"				=> array(
			"page callback"		=> "offer2buy_dashboard",
			"page arguments"	=> array(1),
			"access arguments"	=> array("offer2buy admin"),
			"file"				=> "offer2buy.actions.php",
			"type"				=> MENU_CALLBACK,
		),
		"offer2buy/ajax/offer/%"	=> array(
			"page callback"		=> "offer2buy_ajax_offer",
			"page arguments"	=> array(3),
			"file"				=> "offer2buy.ajax.php",
			"access arguments"	=> array("offer2buy offer"),
			"type"				=> MENU_CALLBACK,
		),
		"offer2buy/ajax/edit-post-type/%"	=> array(
			"page callback"		=> "offer2buy_ajax_edit_post_type",
			"page arguments"	=> array(3),
			"access callback"	=> "offer2buy_change_list_type_access",
			"access arguments"	=> array(3),
			"file"				=> "offer2buy.forms.php",
		),
		"admin/settings/offer2buy"	=> array(
			"title"				=> "Offer2Buy",
			"description"		=> t("Control offer2buy email messages"),
			"page callback"		=> "drupal_get_form",
			"page arguments"	=> array("offer2buy_admin"),
			"access arguments"	=> array("offer2buy admin"),
			"file"				=> "offer2buy.forms.php",
			"type"				=> MENU_NORMAL_ITEM,
		),
	);
}

function offer2buy_views_api()
{
	return array(
		"api"	=> 2,
	);
}

function offer2buy_form_vibio_item_node_form_alter(&$form, &$state)
{
	$nid = $form['nid']['#value'];
	$settings = offer2buy_get_settings($nid);
	
	$form['offer2buy'] = array(
		"#type"				=> "fieldset",
		"#title"			=> t("Offer to Buy Settings"),
		"#description"		=> t('These options only affect your posting if this item is set to type "selling"'),
		"#collapsible"		=> true,
		"#collapsed"		=> false,
		"#weight"			=> -8,
	);
	
	$form['offer2buy'] = array_merge($form['offer2buy'], _offer2buy_fields_form($nid, $settings));
	
	$form['#validate'][] = "_offer2buy_node_validate";
	$form['#submit'][] = "_offer2buy_node_submit";
}

function _offer2buy_fields_form($nid, $settings)
{
	return array(
		"o2b_price"				=> array(
			"#type"			=> "textfield",
			"#title"		=> t("Price"),
			"#description"	=> t("The listing price for this item (in USD)"),
			"#default_value"=> $settings['price'],
			"#size"			=> 8,
		),
		"o2b_is_negotiable"		=> array(
			"#type"			=> "checkbox",
			"#title"		=> t("Price is Negotiable"),
			"#description"	=> t("This determines whether or not you want to allow other users to offer more or less for the item."),
			"#default_value"=> $settings['is_negotiable'],
		),
		"o2b_allow_offer_views"	=> array(
			"#type"			=> "checkbox",
			"#title"		=> t("Allow Offer Views"),
			"#description"	=> t("Should people viewing your item be able to see the offers on the item?"),
			"#default_value"=> $settings['allow_offer_views'],
		),
		"o2b_nid"				=> array(
			"#type"	=> "value",
			"#value"=> $nid,
		),
	);
}

function _offer2buy_node_validate($form, &$state)
{
	if ($state['values']['field_posting_type'][0]['value'] != VIBIO_ITEM_TYPE_SELL)
	{
		return; //only care about validating input if the posting type is "sell"
	}
	
	if (!_offer2buy_valid_price($state['values']['o2b_price']))
	{
		form_set_error("o2b_price", t("Invalid price definition."));
	}
}

function _offer2buy_node_submit($form, &$state)
{
	return;
}

function offer2buy_nodeapi(&$node, $op, $a3=null, $a4=null)
{
	if ($node->type == "vibio_item")
	{
		switch ($op)
		{
			case "load":
				global $user;
				
				$settings = offer2buy_get_settings($node->nid);
				
				if ($node->uid == $user->uid || $settings['allow_offer_views'])
				{
					$sql = "SELECT o.*, u.`name`
							FROM {offer2buy_offers} o JOIN {users} u
								ON o.`uid`=u.`uid`
							WHERE `nid`=%d
							ORDER BY `offer` DESC, `timestamp` ASC";
					$res = db_query($sql, $node->nid);
					
					$offers = array();
					while ($row = db_fetch_array($res))
					{
						$offers[] = $row;
					}
				}
				
				return array(
					"offer2buy"	=> array(
						"type"		=> $node->field_posting_type[0]['value'],
						"settings"	=> $settings,
						"offers"	=> $offers,
					),
				);
				
				break;
			case "update":
			case "insert":
				$on_sale = $node->field_posting_type[0]['value'] == VIBIO_ITEM_TYPE_SELL;
				$current_settings = offer2buy_get_settings($node->nid);
				
				if ($on_sale)
				{
					$price = number_format($node->o2b_price, 2);
					
					if (!$current_settings['is_on_sale'])
					{
						module_invoke_all("offer2buy_set_item_on_sale", $node->nid);
						$sql = "REPLACE INTO {offer2buy}
								SET `nid`=%d, `price`=%f, `is_negotiable`=%d, `allow_offer_views`=%d, `is_on_sale`=1";
						db_query($sql, $node->nid, $price, $node->o2b_is_negotiable, $node->o2b_allow_offer_views);
					}
					else
					{
						$sql = "UPDATE {offer2buy}
								SET `price`=%f, `is_negotiable`=%d, `allow_offer_views`=%d, `is_on_sale`=1
								WHERE `nid`=%d";
						db_query($sql, $price, $node->o2b_is_negotiable, $node->o2b_allow_offer_views, $node->nid);
					}
				}
				else
				{
					$sql = "UPDATE {offer2buy}
							SET `is_on_sale`=0
							WHERE `nid`=%d";
					db_query($sql, $node->nid);
				}
				
				break;
			default:
				break;
		}
	}
}

function offer2buy_theme(&$existing, $type, $theme, $path)
{
	return array(
		"offer2buy_init"		=> array(
			"arguments"	=> array("nid" => false),
			"template"	=> "templates/offer2buy/init",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"offer2buy_list_all_offers"	=> array(
			"arguments"	=> array("items" => array()),
			"template"	=> "templates/offer2buy/all-offers",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"offer2buy_list_outgoing_offers" => array(
			"arguments"	=> array("offers" => array()),
			"template"	=> "templates/offer2buy/outgoing-offers",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"offer2buy_offer_list"	=> array(
			"arguments"	=> array("offers" => array(), "is_owner" => false),
			"template"	=> "templates/offer2buy/list",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"offer2buy_offer"		=> array(
			"arguments"	=> array("offer" => array(), "is_owner" => false),
			"template"	=> "templates/offer2buy/offer",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"offer2buy_actions_list"=> array(
			"arguments"	=> array("list"	=> array(), "type" => "required"),
			"template"	=> "templates/offer2buy/action-list",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"offer2buy_action_item"	=> array(
			"arguments"	=> array("action"	=> array(), "type" => "required"),
			"template"	=> "templates/offer2buy/action-item",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
		"offer2buy_existing_offers_popup" => array(
			"arguments"	=> array("offer_list"	=> array()),
			"template"	=> "templates/offer2buy/offer-popup",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
	);
}

function offer2buy_get_settings($nid=false)
{
	if (!$nid)
	{
		return false;
	}
	
	$sql = "SELECT *
			FROM {offer2buy}
			WHERE `nid`=%d";
	return db_fetch_array(db_query($sql, $nid));
}

function offer2buy_preprocess_node(&$vars)
{
	if (!$vars['teaser'] && $vars['node']->type == "vibio_item")
	{
		drupal_add_css("themes/vibio/css/offer2buy.css");
		drupal_add_js("themes/vibio/js/offer2buy.js");
	}
}

function offer2buy_preprocess_page(&$vars)
{
	drupal_add_js("themes/vibio/js/offer2buy_actions.js");
}

function offer2buy_get_offer($uid, $nid)
{
	$sql = "SELECT *
			FROM {offer2buy_offers}
			WHERE `uid`=%d
				AND `nid`=%d";
	return db_fetch_array(db_query($sql, $uid, $nid));
}

function offer2buy_offer_form(&$state, $nid, $referrer)
{
	global $user;
	
	$settings = offer2buy_get_settings($nid);
	$current_offer = offer2buy_get_offer($user->uid, $nid);
	
	$form = array(
		"uid"		=> array(
			"#type"	=> "value",
			"#value"=> $user->uid,
		),
		"nid"		=> array(
			"#type"	=> "value",
			"#value"=> $nid,
		),
		"destination"	=> array(
			"#type"	=> "value",
			"#value"=> empty($_GET['destination']) ? request_uri() : $_GET['destination'],
		),
		"offer"		=> array(
			"#type"			=> "textfield",
			"#title"		=> t("Offer"),
			"#default_value"=> $current_offer ? $current_offer['offer'] : $settings['price'],
		),
		"comment"	=> array(
			"#type"			=> "textarea",
			"#title"		=> t("Comment"),
			"#description"	=> t("A comment that the seller will see when reviewing offers for this item."),
			"#default_value"=> $current_offer['comment'],
		),
		"submit"	=> array(
			"#type"	=> "submit",
			"#value"=> t("Offer"),
		),
	);
	
	if (!$settings['is_negotiable'])
	{
		$form['offer']['#attributes'] = array(
			"readonly"	=> "readonly",
		);
	}
	
	if ($current_offer)
	{
		$form['#prefix'] = t("You already have a pending offer on this item. The details of that offer are shown below. Any edits will replace your original offer.");
	}
	
	return $form;
}

function offer2buy_offer_form_validate($form, &$state)
{
	$vals = $state['values'];
	$error = false;
	
	if (!_offer2buy_valid_price($vals['offer']))
	{
		form_set_error("offer", t("Invalid offer amount"));
		$error = true;
	}
	elseif (strlen($vals['comment']) > OFFER2BUY_MAX_COMMENT_LENGTH)
	{
		form_set_error("comment", t("Comment cannot exceed !limit characters", array("!limit" => OFFER2BUY_MAX_COMMENT_LENGTH)));
		$error = true;
	}
	
	if ($error)
	{
		drupal_goto($vals['destination']);
	}
}

function offer2buy_offer_form_submit($form, &$state)
{
	$vals = $state['values'];
	$offer = number_format($vals['offer'], 2);
	
	$sql = "REPLACE INTO {offer2buy_offers}
			SET `nid`=%d, `uid`=%d, `offer`=%f, `timestamp`=%d, `comment`='%s'";
	db_query($sql, $vals['nid'], $vals['uid'], $offer, time(), $vals['comment']);
	
	$node = node_load($vals['nid']);
	$offerer = user_load($vals['uid']);
	$item_owner = user_load($node->uid);
	$offer = array(
		"comment"	=> $vals['comment'],
		"amount"	=> $offer,
	);
	
	module_invoke_all("offer2buy_make_offer", $node, $offerer, $item_owner, $offer);
	
	drupal_set_message(t("Your offer has been sent to !user", array("!user" => $item_owner->name)));
	drupal_goto($vals['destination']);
}

function offer2buy_offer2buy_make_offer($node, $offerer, $owner, $offer)
{
	global $language;
	
	$params = array(
		"offerer"	=> $offerer,
		"owner"		=> $owner,
		"offer"		=> $offer,
		"item"		=> $node,
	);
	
	drupal_mail("offer2buy", "offer_make", $owner->mail, $language, $params);
	drupal_mail("offer2buy", "offer_make_confirm", $offerer->mail, $language, $params);
}

function offer2buy_offerbuy_accept_offer($node, $offerer, $owner, $offer)
{
	global $user;
	
	_offer2buy_cancel_transaction($node->nid, $user->uid, false);
	
	$params = array(
		"item"		=> $node,
		"offerer"	=> $offerer,
		"owner"		=> $owner,
		"offer"		=> $offer,
	);
	
	drupal_mail("offer2buy", "offer_accept", $offerer->mail, $language, $params);
	drupal_mail("offer2buy", "offer_accept_confirm", $owner->mail, $language, $params);
}

function offer2buy_mail($key, &$message, $params)
{
	if ($key == "offer_make" && ($body = variable_get("offer2buy_offer_message", false)))
	{
		$message['subject'] = t("Offer on \"!title\" from !user", array("!title" => $params['item']->title, "!user" => $params['offerer']->name));
		$message['body'] = _offer2buy_replace($body, $params);
	}
	elseif ($key == "offer_make_confirm" && ($body = variable_get("offer2buy_offer_confirmation", false)))
	{
		$message['subject'] = t("Confirmation for offer to !user for item \"!item\"", array("!user" => $params['owner']->name, "!item" => $params['item']->title));
		$message['body'] = _offer2buy_replace($body, $params);
	}
	elseif ($key == "offer_accept" && ($body = variable_get("offer2buy_offer_accept", false)))
	{
		$message['subject'] = t("Offer accepted for \"!item\"!", array("!item" => $params['item']->title));
		$message['body'] = _offer2buy_replace($body, $params);
	}
	elseif ($key == "offer_accept_confirm" && ($body = variable_get("offer2buy_offer_accept_confirm", false)))
	{
		$message['subject'] = t("Offer acceptance confirmation: \$!offer from !offerer", array("!offer" => $params['offer']['amount'], "!offerer" => $params['offerer']->name));
		$message['body'] = _offer2buy_replace($body, $params);
	}
}

function _offer2buy_valid_price($price)
{
	if (!is_numeric($price))
	{
		return false;
	}
	
	$price = number_format($price, 2);
	return $price >= 0 && $price <= OFFER2BUY_MAX_PRICE;
}

function _offer2buy_replace($message, $params)
{
	$link_options = array(
		"absolute"	=> true,
	);
	
	$private_msg_subject = "{$params['item']->title}";
	
	$replacements = array(
		"!offerer_message_url"	=> url("messages/new/{$params['offerer']->uid}/$private_msg_subject", $link_options),
		"!owner_message_url"	=> url("messages/new/{$params['owner']->uid}/$private_msg_subject", $link_options),
		"!offerer"				=> l($params['offerer']->name, "user/{$params['offerer']->uid}", $link_options),
		"!owner"				=> l($params['owner']->name, "user/{$params['owner']->uid}", $link_options),
		"!item"					=> l($params['item']->title, "node/{$params['item']->nid}", $link_options),
		"!comment"				=> filter_xss($params['offer']['comment']),
		"!offer"				=> $params['offer']['amount'],
	);
	
	foreach ($replacements as $search => $replace)
	{
		$message = str_replace($search, $replace, $message);
	}
	
	return $message;
}

function offer2buy_forms($id, $args)
{
	if (strpos($id, "offer2buy_offer_accept_form_") !== false)
	{
		$forms[$id] = array(
			"callback"	=> "offer2buy_offer_accept_form",
		);
		
		return $forms;
	}
	elseif (strpos($id, "offer2buy_action_complete_") !== false)
	{
		$forms[$id] = array(
			"callback"	=> "offer2buy_action_complete_form",
		);
		
		return $forms;
	}
	elseif (strpos($id, "offer2buy_transaction_cancel_") !== false)
	{
		$forms[$id] = array(
			"callback"	=> "offer2buy_transaction_cancel_form",
		);
		
		return $forms;
	}
}

function offer2buy_transaction_cancel_form(&$state, $nid)
{
	global $user;
	
	return array(
		"nid"		=> array(
			"#type"	=> "value",
			"#value"=> $nid,
		),
		"canceller"	=> array(
			"#type"	=> "value",
			"#value"=> $user->uid,
		),
		"submit"	=> array(
			"#type"	=> "submit",
			"#value"=> t("Cancel"),
		),
		"#submit"	=> array(
			"offer2buy_transaciton_cancel_form_submit",
		),
		"#attributes"	=> array(
			"class"	=> "offer2buy_transaction_cancel_form",
		),
	);
}

function offer2buy_transaciton_cancel_form_submit($form, &$state)
{
	_offer2buy_cancel_transaction($state['values']['nid'], $state['values']['canceller']);
}

function offer2buy_offer_accept_form(&$state, $uid, $nid)
{
	if (offer2buy_offer_is_pending($uid, $nid))
	{
		return array(
			"pending"	=> array(
				"#value"	=> "<span class='offer2buy_pending_offer'>".t("(pending)")."</span>",
			),
		);
	}
	
	return array(
		"uid"		=> array(
			"#type"	=> "value",
			"#value"=> $uid,
		),
		"nid"		=> array(
			"#type"	=> "value",
			"#value"=> $nid,
		),
		"submit"	=> array(
			"#type"	=> "submit",
			"#value"=> t("Accept Offer"),
		),
		"#submit"	=> array(
			"offer2buy_offer_accept_form_submit",
		),
		"#attributes"	=> array(
			"class"	=> "offer2buy_offer_accept_form",
		),
	);
}

function offer2buy_offer_accept_form_submit($form, &$state)
{
	$vals = $state['values'];
	$node = node_load($vals['nid']);
	$offerer = user_load($vals['uid']);
	$owner = user_load($node->uid);
	
	$sql = "SELECT `offer` AS amount, `comment`
			FROM {offer2buy_offers}
			WHERE `uid`=%d
				AND `nid`=%d";
	$offer = db_fetch_array(db_query($sql, $offerer->uid, $node->nid));
	
	module_invoke_all("offerbuy_accept_offer", $node, $offerer, $owner, $offer);
	_offer2buy_init_actions($node->nid, $offerer->uid, $owner->uid);
}

function offer2buy_offer2buy_complete_actions($old_owner_uid, $node)
{
	$sql = "SELECT `offer`
			FROM {offer2buy_offers}
			WHERE `nid`=%d
				AND `uid`=%d";
	$price = db_result(db_query($sql, $node->nid, $node->uid));
	
	$sql = "INSERT INTO {offer2buy_completed_transactions}
			(`nid`, `buyer`, `seller`, `price`, `timestamp`)
			VALUES
			(%d, %d, %d, %f, %d)";
	db_query($sql, $node->nid, $node->uid, $old_owner_uid, $price, time());
	
	$sql = "DELETE FROM {offer2buy}
			WHERE `nid`=%d";
	db_query($sql, $node->nid);
}

function offer2buy_change_list_type_access($nid)
{
	global $user;
	
	$sql = "SELECT `uid`
			FROM {node}
			WHERE `nid`=%d";
	$uid = db_result(db_query($sql, $nid));		
	
	return $uid == $user->uid;
}

function offer2buy_reports_daily_cron($last_run)
{
	$sql = "SELECT COUNT(*) total_transactions, SUM(`price`) amount_transacted
			FROM {offer2buy_completed_transactions}
			WHERE `timestamp` > %d";
	$res = db_query($sql, $last_run);
	
	if ($row = db_fetch_object($res))
	{
		reports_log("total transactions", $row->total_transactions);
		reports_log("amount transacted", $row->amount_transacted);
	}
}
?>