<?php
define("REPORT_DEFAULT_START", 60*60*24*7); //one week ago
define("REPORT_RUN_INTERVAL", 60*60*24); //one day
define("REPORT_ONE_HOUR", 60*60);

function reports_perm()
{
	return array(
		"reports view",
		"reports admin",
	);
}

// each module is individually responsible for calling db_set_active!
function reports_cron()
{
	module_load_include("inc", "reports");
	
	$last_daily_run = variable_get("reports_last_daily_run", 0);
	$now = time();
	
	module_invoke_all("reports_cron");
	
	if (date("G") == variable_get("reports_hour", 0) && $now - $last_daily_run > REPORT_RUN_INTERVAL - REPORT_ONE_HOUR) // make sure this is only run once a day
	{
		module_invoke_all("reports_daily_cron", $last_daily_run);
		variable_set("reports_last_daily_run", $now);
	}
}

function reports_reports_daily_cron($last_run)
{
	reports_total_users();
	reports_new_users($last_run);
}

function reports_menu()
{
	return array(
		"admin/settings/reports"=> array(
			"title"				=> "Reports",
			"page callback"		=> "drupal_get_form",
			"page arguments"	=> array("reports_settings"),
			"access arguments"	=> array("reports admin"),
			"file"				=> "reports.pages.inc",
			"type"				=> MENU_NORMAL_ITEM,
		),
		"reports"				=> array(
			"title"				=> "Reports",
			"page callback"		=> "reports_overview",
			"access arguments"	=> array("reports view"),
			"file"				=> "reports.pages.inc",
			"type"				=> MENU_CALLBACK,
		),
		"reports/%"				=> array(
			"page callback"		=> "reports_view_report",
			"page arguments"	=> array(1),
			"access arguments"	=> array("reports view"),
			"file"				=> "reports.pages.inc",
			"type"				=> MENU_CALLBACK,
		),
	);
}

function reports_theme(&$existing, $type, $theme, $path)
{
	return array(
		"reports_view_report"	=> array(
			"arguments"	=> array("selector" => false),
			"template"	=> "templates/reports/view",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
	);
}

function reports_load($name, $from=false, $to=false, $hide_employees=true)
{
	$db = db_set_active("reports");
	$from = $from ? $from : time() - REPORT_DEFAULT_START;
	$to = $to ? $to : time();
	//the extra hour is  because we don't know exactly when the cron was run, so the timestamp will be a little off.
	$from += variable_get("reports_hour", 0)*REPORT_ONE_HOUR;
	$to += variable_get("reports_hour", 0)*REPORT_ONE_HOUR + REPORT_ONE_HOUR;
	
	$name = $hide_employees ? $name." noemployee" : $name;
	
	$sql = "SELECT *
			FROM {reports}
			WHERE `name`='%s'
				AND `tstamp` BETWEEN %d AND %d
			ORDER BY `tstamp` ASC";
	$res = db_query($sql, $name, $from, $to); 
	db_set_active($db);
	
	$report = array();
	while ($row = db_fetch_object($res))
	{
		$row->tstamp = 1000*($row->tstamp + REPORT_ONE_HOUR*variable_get("reports_offset", 0)); //x1000 is to convert unix timestamps into js timestamps.
		$report[] = $row;
	}
	
	return $report;
}
?>
