<?php

/**
 * Implements hook_preprocess_node() to assist with sharing items on Vibio.
 *
 * -Adds Open Graph data to products
 * -Loads the product image (product template file is coded to make this
 * non-essential)
 *
 * @param <type> $variables
 */
function vibio_addthis_preprocess_node(&$variables){
  $node = $variables['node'];
  //Rules for setting product OG meta data
  if($node->type == 'product'){
    //Getting the image URL
    $image = _product_get_image($node->nid, true);
    if(!empty($image)){
      $og_image = '<meta property="og:image" content="'. $image . '" />';
      $variables['product_image'] = $image;
    }else{
      $og_image = '<meta property="og:image" content="'. url('themes/vibio/vibio-logo.png') . '" />';
      $variables['product_image'] = url('themes/vibio/images/icons/default_item_large.png');
    }

    $og_title = '<meta property="og:title" content="'. $node->title . '" />';
    //Description: message on Facebook wall. Check copy?
    $description = 'Check it out on Vibio!';
    $og_description = '<meta property="og:description" content="'. $description .'" />';
    $og_tags = $og_image . PHP_EOL . $og_title . PHP_EOL . $og_description;
    drupal_set_html_head($og_tags);
  }
}

