<?php
function hbi_user_relationships($op, &$relationship)
{
	switch ($op)
	{
		case "approve":
		case "remove":
			_hbi_set_relationship($op, $relationship);
			break;
	}
}

function _hbi_set_relationship($op, &$relationship)
{
	$message_id = $op == "approve" ? "heartbeat_become_friends" : "heartbeat_cancel_friendship";
	$variables = array(
		"@user1" 		=> l($relationship->requestee->name, "user/".$relationship->requestee->uid),
		"@relation_type"=> $relationship->name,
		"@user2"		=> l($relationship->requester->name, "user/".$relationship->requester->uid),
		"duplicate"		=> 1,
	);
	
	heartbeat_api_log($message_id, $relationship->requestee->uid, $relationship->requester->uid, 0, 0, $variables);
	
	$var_reverse = $variables;
	$var_reverse['@user1'] = $variables['@user2'];
	$var_reverse['@user2'] = $variables['@user1'];
	
	heartbeat_api_log($message_id, $relationship->requester->uid, $relationship->requestee->uid, 0, 0, $var_reverse);
}
?>