<?php
// $Id: amazon_search.module,v 1.1.2.1 2010/02/25 06:41:30 rfay Exp $


function amazon_search_perm() {
  return array('access amazon search');
}

/**
 * Implementation of hook_search(). Implements remote Amazon searching.
 */
function amazon_search_search($op = 'search', $keys = NULL, $skip_access_check = FALSE) {
  switch ($op) {
    case 'name':
      if ($skip_access_check || user_access('access amazon search')) {
        return t('Amazon.com');
      }
    case 'search':
      if ($skip_access_check || user_access('access amazon search')) {
        $products = array();
        $items = amazon_search_simple_search($keys);
        foreach ($items as $item) {
          if (module_exists("vibio_amazon"))
          {
            amazon_item_insert($item);
            $products[] = _vibio_amazon_search_result($item);
          }
          else
          {
            $products[] = array(
              'title' => check_plain($item['title']),
              'link' => check_url($item['detailpageurl']),
              'type' => check_plain($item['productgroup']),
              'user' => isset($item['participants']) ? implode(', ', $item['participants']) : '',
              'snippet' => isset($item['editorialreviews']) ? check_markup($item['editorialreviews'][0]['content']) : '',
            );
          }
        }
        return $products;
      }
  }
}

function amazon_search_simple_search($keywords = '', $parameters = array()) {
  global $pager_page_array, $pager_total;
  $pager_element = is_array($pager_page_array) && !empty($pager_page_array) ? count($pager_page_array) : 0;
  $current_page = $_GET['page'] ? $_GET['page'] : 0;
  
  $parameters += array(
    'ResponseGroup' => 'Large',
    'SearchIndex'   => 'All',
    'TagPage'      => $current_page + 1,
  );
  $parameters['Keywords'] = urlencode($keywords);
  drupal_alter('amazon_search_parameters', $parameters);

  $items = array();
  $results = amazon_http_request('ItemSearch', $parameters);
  
  $pager_page_array[$pager_element] = $current_page;
  $pager_total[$pager_element] = (int) $results->Items->TotalPages;
  
  foreach($results->Items->Item as $xml) {
    $item = amazon_item_clean_xml($xml);
    $items[$item['asin']] = $item;
  }
  return $items;
}