<?php
function uri_menu()
{
	$menu = array(
		"relationships/edit-elaboration/%"	=> array(
			"title"				=> "Edit Friend Details",
			"page callback"		=> "uri_edit_elaboration",
			"page arguments"	=> array(2),
			"access arguments"	=> array("can have relationships"),
			"file"				=> "uri.pages.inc",
			"type"				=> MENU_CALLBACK,
		),
	);
	
	// user_relationships_ui.module has something similar, but we went everything to be ajax-y fancy pants, so we must provide our own callbacks
	foreach (array('approve', 'disapprove', 'cancel') as $action)
	{
		$menu["relationships/%user/%/{$action}"] = array(
			"title"				=> "Pending Relationship Action",
			"access callback"	=> "user_relationships_ui_check_access",
			"access arguments"	=> array(array("admin", "user"), 1),
			"page callback"		=> "uri_pending_request_action",
			"page arguments"	=> array($action, 1, 2),
			"file"				=> "uri.forms.inc",
			"type"				=> MENU_CALLBACK,
		);
	}
	
	$menu["relationships/%user/%user_relationships/remove"] = array(
		"title"				=> "Remove Relationship",
		"access callback"	=> "user_relationships_ui_check_access",
		"access arguments"	=> array(array("admin", "user"), 1),
		"page callback"		=> "uri_remove_relationship",
		"page arguments"	=> array(1, 2),
		"file"				=> "uri.forms.inc",
		"type"				=> MENU_CALLBACK,
	);
	
	$menu["relationships/%user/%user_relationships_type/request"] = array(
		"title"				=> "Request Relationship",
		"access callback"	=> "user_relationships_ui_check_access",
		"access arguments"	=> array("edit"),
		"page callback"		=> "uri_request_relationship",
		"page arguments"	=> array(1, 2),
		"file"				=> "uri.forms.inc",
		"type"				=> MENU_CALLBACK,
	);
	
	return $menu;
}

function uri_menu_alter(&$menu)
{
	$menu['relationships/list']['title'] = 'Connections';
	
	foreach (user_relationships_types_load() as $rtid => $relationship)
	{
		$menu["relationships/{$rtid}"]['type'] = MENU_CALLBACK;
	}
}

function uri_preprocess_user_relationships(&$vars)
{	
	$link_options = array(
		"attributes"	=> array(
			"class"	=> "uri_edit_elaboartion",
		),
	);
	
	foreach ($vars['relationships'] as $rid => $rel)
	{
		$link = l(t("edit details"), "relationships/edit-elaboration/$rid", $link_options);
		$vars['relationships'][$rid]->extra_for_display = "
			<span class='uri_elaboration'>{$rel->extra_for_display}</span>
			($link)
		";
	}
}

function uri_preprocess_page(&$vars)
{
	drupal_add_js("sites/all/themes/vibio/js/uri.js");
	drupal_add_css("sites/all/themes/vibio/css/uri.css");
}

function uri_preprocess_user_profile(&$vars)
{
	global $user;
	
	if ($action_links = _user_relationships_ui_actions_between($user, $vars['account']))
	{
		$vars['profile']['uri_actions']['actions'] = theme("uri_action_list", $action_links);
	}
}

function uri_theme()
{
	return array(
		"uri_action_list"	=> array(
			"arguments"	=> array("list" => array()),
			"template"	=> "templates/uri/action-list",
			"path"		=> drupal_get_path("theme", "vibio"),
		),
	);
}

function uri_edit_elaboration_form()
{
	return array(
		"#attributes"	=> array(
			"class"	=> "uri_edit_elaborations_form",
		),
		"container"		=> array(
			"#type"			=> "fieldset",
			"#title"		=> t("Edit Friend Details"),
			"#collapsible"	=> false,
			"elaboration"	=> array(
				"#title"		=> t("Elaboration"),
				"#description"	=> t("How do you know !user? Keep in mind that both you and !user are able to view this.", array("!user" => "<span class='uri_elaboration_target'></span>")),
				"#type"			=> "textarea",
			),
			"submit"		=> array(
				"#type"	=> "submit",
				"#value"=> t("Save"),
			),
		),
	);
}
?>